stages: 
  - build
  - deploy

build_docker: 
  stage: build
  script: 
    - "docker build --no-cache --rm -t noderp/web-frontend:$CI_COMMIT_SHA ."
  only: 
    - develop
  
deploy_docker: 
  stage: deploy
  script: 
    - "docker save noderp/web-frontend:$CI_COMMIT_SHA | gzip > ./latest.tar.gz"
    - "scp ./latest.tar.gz root@dev.pc-rpg.com.br:/tmp"
    - "ssh root@dev.pc-rpg.com.br \"docker load < /tmp/latest.tar.gz\""
  only: 
    - develop
