stages: 
  - build
  - deploy

variables: 
  DEPLOY_SSH_URI: root@pcrpg-br-app-prod-1
  DOCKER_IMAGE_NAME: noderp/web-frontend
  DOWNSTREAM_PROJECT_ID: 9203660

build_docker: 
  stage: build
  before_script: 
    - export CI_COMMIT_SHA_SHORT=${CI_COMMIT_SHA::8}
  script: 
    - "docker build --build-arg SSH_KEY=\"$(cat ~/.ssh/id_rsa)\" --no-cache --rm -t $DOCKER_IMAGE_NAME:${CI_COMMIT_SHA_SHORT} ."
  only: 
    - master
    - develop
    - tags
    - triggers
    - run
  tags: 
    - internal
    - shell
  
deploy_docker: 
  stage: deploy
  before_script: 
    - export CI_COMMIT_SHA_SHORT=${CI_COMMIT_SHA::8}
  script: 
    - "docker save $DOCKER_IMAGE_NAME:${CI_COMMIT_SHA_SHORT} | gzip > ./$CI_PROJECT_PATH_SLUG-${CI_COMMIT_SHA_SHORT}.tar.gz"
    - "scp ./$CI_PROJECT_PATH_SLUG-${CI_COMMIT_SHA_SHORT}.tar.gz $DEPLOY_SSH_URI:/tmp"
    - "ssh $DEPLOY_SSH_URI \"docker load < /tmp/$CI_PROJECT_PATH_SLUG-${CI_COMMIT_SHA_SHORT}.tar.gz && docker tag $DOCKER_IMAGE_NAME:${CI_COMMIT_SHA_SHORT} $DOCKER_IMAGE_NAME:latest\""
  after_script:
    - "docker rmi -f $DOCKER_IMAGE_NAME:${CI_COMMIT_SHA::8}"
    - "curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$DOWNSTREAM_PROJECT_ID/trigger/pipeline"
  only: 
    - master
  tags: 
    - internal
    - shell
 