stages: 
  - build
  - deploy

build_docker: 
  stage: build
  script: 
    - "docker build --no-cache --rm -t noderp/web-frontend:$CI_COMMIT_REF_NAME ."
  only: 
    - develop
  
deploy_docker: 
  stage: deploy
  script: 
    - "docker save noderp/web-frontend:$CI_COMMIT_REF_NAME | gzip > ./latest.tar.gz"
    - "scp ./latest.tar.gz root@dev.pc-rpg.com.br:/tmp"
    - "ssh root@dev.pc-rpg.com.br \"docker load < /tmp/latest.tar.gz\""
  after_script:
    - "docker rmi noderp/web-frontend:$CI_COMMIT_REF_NAME"
    - "curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/9203660/trigger/pipeline"
  only: 
    - develop
